# Generated by Django 2.2.3 on 2019-08-25 19:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pizza.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20190825_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[pizza.models.code_validator])),
                ('method', models.CharField(choices=[('ONL', 'Online'), ('VISA', 'Visa'), ('RUPAY', 'RuPay'), ('PAYTM', 'PayTM'), ('MASTR', 'Master Card'), ('DBTC', 'Debit Card'), ('CRDT', 'Credit Card'), ('COD', 'Cash On Delivery'), ('RAZP', 'RazorPay')], max_length=5)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=1, max_length=5, unique=True, validators=[pizza.models.code_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 1, 20, 52, 219867)),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza', verbose_name='pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Size', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.PizzaType', verbose_name='pizza type'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=8)),
                ('maximum', models.FloatField(default=0.0)),
                ('percent', models.FloatField(default=0.0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.UserSource', verbose_name='source')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.Discount', verbose_name='discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.Payment', verbose_name='payment'),
            preserve_default=False,
        ),
    ]
